export const services = [
  {
    id: "1",
    title: "General Diagnostics",
    slug: "general-diagnostics",
    description: "Experience world-class general diagnostic care. From precise early diagnostics to comprehensive evaluations, our elite specialists are dedicated to restoring your vitality and extending your life.",
    imageUrl: "/1general.jpeg",
    iconName: "Activity",
  },
  {
    id: "2",
    title: "IVF & Fertility Clinic",
    slug: "ivf-fertility",
    description: "Your journey to parenthood, guided by expertise and profound empathy. We leverage state-of-the-art Assisted Reproductive Technology (ART) to turn your dream of a family into a beautiful reality.",
    imageUrl: "/ivf-fertility.jpg",
    iconName: "Baby",
  },
  {
    id: "3",
    title: "Obstetrics & Gynecology",
    slug: "obstetrics-gynecology",
    description: "Comprehensive, compassionate care for every stage of womanhood. We offer premier maternal support, high-risk pregnancy management, and advanced gynecological solutions.",
    imageUrl: "/obstetrics-gynecology.jpg",
    iconName: "Users",
  },
  {
    id: "4",
    title: "Orthopedics & Trauma",
    slug: "orthopedics",
    description: "Regain your freedom of movement. Our trauma experts and orthopedic surgeons utilize cutting-edge techniques for complex fractures, joint reconstruction, and rapid sports recovery.",
    imageUrl: "/orthopedics.jpg",
    iconName: "Bone",
  },
  {
    id: "5",
    title: "Oncology Center",
    slug: "oncology",
    description: "Unwavering support in your fight against cancer. We provide highly personalized, aggressive treatment plans combining advanced radiotherapy, chemotherapy, and surgical oncology.",
    imageUrl: "/oncology.jpg",
    iconName: "Activity",
  },
  {
    id: "6",
    title: "Pediatrics & Neonatology",
    slug: "pediatrics",
    description: "Exceptional care for your most precious miracles. Our renowned pediatricians and Level III NICU ensure your child receives the highest standard of medical attention from day one.",
    imageUrl: "/pediatric.jpg",
    iconName: "Stethoscope",
  },
  {
    id: "7",
    title: "Internal Medicine & Nephrology",
    slug: "internal-medicine",
    description: "Proactive, holistic management of complex adult diseases. Featuring an ultra-modern dialysis center and comprehensive strategies for kidney health and chronic condition reversal.",
    imageUrl: "/internal.jpg",
    iconName: "Microscope",
  },
  {
    id: "8",
    title: "24/7 Emergency & ICU",
    slug: "emergency-care",
    description: "Critical care without compromise. Our rapid-response emergency department and high-tech Intensive Care Units stand ready 24/7 to deliver life-saving interventions when seconds matter.",
    imageUrl: "/247_emergency.jpg",
    iconName: "Ambulance",
  },
  {
    id: "9",
    title: "Minimally Invasive Surgery",
    slug: "surgery",
    description: "Surgical excellence with accelerated recovery. Our state-of-the-art suites specialize in precision laparoscopic operations, minimizing trauma and returning you to daily life faster.",
    imageUrl: "/minimal.jpg",
    iconName: "Scissors", 
  },
  {
    id: "10",
    title: "Advanced Diagnostics",
    slug: "imaging-diagnostics",
    description: "Clarity you can trust. Our automated laboratories and high-definition imaging suites (MRI, CT, digital X-ray) provide the rapid, accurate insights necessary for targeted treatment.",
    imageUrl: "/advance.jpg",
    iconName: "Monitor",
  },
  {
    id: "11",
    title: "Neurology",
    slug: "neurology",
    description: "Pioneering care for the nervous system. We deliver sophisticated diagnoses and innovative treatments for complex disorders affecting the brain and spinal cord.",
    imageUrl: "/neurology.jpg",
    iconName: "Brain",
  },
  {
    id: "12",
    title: "Physical Rehabilitation",
    slug: "physical-rehabilitation",
    description: "Empowering your recovery. Our bespoke physiotherapy programs are designed to meticulously rebuild strength, restore mobility, and elevate your overall quality of life.",
    imageUrl: "/physical.jpg",
    iconName: "Activity",
  },
  {
    id: "13",
    title: "Antenatal and Maternity Care",
    slug: "antenatal-maternity-care",
    description: "Comprehensive care for expectant mothers. From routine check-ups to specialized labor and delivery, we provide a safe, nurturing environment for both mother and baby throughout the entire pregnancy journey.",
    imageUrl: "/antenantal.jpg",
    iconName: "Baby",
  },
  {
    id: "14",
    title: "24 Hour Services",
    slug: "24-hour-services",
    description: "Healthcare that never sleeps. Our dedicated teams and essential facilities remain fully operational around the clock, ensuring that you have access to critical medical support at any hour of the day or night.",
    imageUrl: "/24_hours.jpg",
    iconName: "Clock",
  },
  {
    id: "15",
    title: "General Nursing Care",
    slug: "general-nursing-care",
    description: "Compassionate, holistic nursing support. Our highly trained nursing staff provides meticulous bedside care, vital sign monitoring, and empathetic support tailored to accelerate your healing process.",
    imageUrl: "/general_nursing.jpg",
    iconName: "HeartPulse",
  },
  {
    id: "16",
    title: "General Medical Care",
    slug: "general-medical-care",
    description: "Your first line of defense for everyday health. From routine physicals to the diagnosis and management of common illnesses, our general practitioners deliver reliable, comprehensive medical care.",
    imageUrl: "/general_medical_care.jpg",
    iconName: "Activity",
  },
  {
    id: "17",
    title: "General Surgical Care",
    slug: "general-surgical-care",
    description: "Expert surgical interventions for a wide range of conditions. Our general surgeons utilize modern techniques to perform both elective and urgent procedures with a focus on safety and rapid recovery.",
    imageUrl: "/general_surgical.jpg",
    iconName: "Scissors",
  },
  {
    id: "18",
    title: "Accident & Emergency Care",
    slug: "accident-emergency-care",
    description: "Immediate, life-saving response when seconds matter. Our trauma-trained emergency physicians are equipped to handle severe injuries, acute illnesses, and complex medical crises with precision and speed.",
    imageUrl: "/accident_and_emergency_care.jpg",
    iconName: "Ambulance",
  }
];

export const doctors = [
  {
    id: "1",
    name: "Dr. Josiah Onuche",
    specialty: "Founder & MD",
    qualifications: "Founder, Chief Medical Director.",
    slug: "founder",
    imageUrl: "/founder1.jpg",
  }
];
